### PR TITLE
Move branch submodule to file + improve test coverage

### PR DESCRIPTION
**Pull request by skirpichev**
On top of #11

### CODE REVIEW

**Comment by skirpichev** [comment]
@mrocklin, maybe you can review these two last prs (#12 and #11)?

**Comment by mrocklin** [comment]
Sorry, I'm going to have to pass.  I'm already quite negligent on several other projects for which I've promised to do work.

**Comment by skirpichev** [comment]
@mrocklin, thank you for reply.

Then I'll think about dropping dependence on this project or forking one.

**Comment by skirpichev** [comment]
btw, probably you should warn people that this project is not maintained anymore.

**Comment by skirpichev** [comment]
@mrocklin, I could help you with maintaining this project (or any other your project from Diofant dependencies), if you trust me.

Unfortunately, you are member of the SymPy project, which adopts Code of Conduct practice (you ban people, remove bugs and so on).  Could you use for this project something like https://github.com/domgetter/NCoC/blob/master/CODE_OF_CONDUCT.md
or, at least, promise publicly that you will follow such practice for contributions here?

**Comment by mrocklin** [comment]
Hi @skirpichev .  I'm probably not going to adopt that code of conduct, nor promise to follow its practices.  

I've stopped maintaining this library.  If you or someone else wants to maitain a standard fork elsewhere that would be welcome.

**Comment by skirpichev** [comment]
> I'm probably not going to adopt that code of conduct, nor promise to follow its practices.

Bad news.

> If you or someone else wants to maitain a standard fork elsewhere that would be welcome.

Thank you, @mrocklin, but I doubt I can reinvent suitable names for all your tiny projects.  Probably, it would be more safe to drop dependency on strategies&co.

**Pull request closed without merging**
