### PR TITLE
Implement some functions from logpy/term.py

### LINKED ISSUE #4: hard deps on logpy?
```
>>> from strategies.traverse import bottom_up
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sk/.virtualenvs/test/local/lib/python2.7/site-packages/strategies/traverse.py", line 3, in <module>
    from logpy.term import operator, arguments, term
ImportError: No module named logpy.term
```

Or you prefer redo `sall` method of strategies/traverse.py like sympy's one?

### PR DESCRIPTION
**Pull request by skirpichev**
This removes hard dependence on logpy and fixes #4.

### CODE REVIEW

**Comment by skirpichev** [comment]
I will merge this in 3 days, if there will be no objections.

Matthew, could you do a minor release after this?

**Comment by mrocklin** [comment]
Looks fine to me

**Comment by mrocklin** [comment]
If you send me your PyPI username (skirpichev?) then I'm happy to provide you with owner privileges on this repository.

**Comment by skirpichev** [comment]
On Sun, Aug 23, 2015 at 09:28:14AM -0700, Matthew Rocklin wrote:
>    If you send me your PyPI username (skirpichev?)

Yes.

>    then I'm happy to provide
>    you with owner privileges on this repository.

Ok, if that make sense for you.

**Comment by mrocklin** [comment]
Done.

**Comment by skirpichev** [comment]
I did a minor release.  sdist still miss tests/\* files, I hope that's ok.

**Pull request merged**
